### ISSUE TITLE
Add Device::cuda()

### ISSUE THREAD

**Issue by Delamare2112** [Twinklebear/oidn-rs#13]
I notice that there is a Device::new() that uses DeviceType::DEFAULT and a Device::cpu() that uses DeviceType::CPU, I think there should be a Device::cuda() no?

**Comment by Twinklebear** [comment]
No, these are just bindings to Intel's OpenImageDenoise, which just has a CPU backend right now: https://github.com/OpenImageDenoise/oidn#device . Wrapping the CUDA/OptiX denoiser would be awesome, but I don't think should be part of oidn-rs (as the name implies, it's just OIDN).

**Comment by Delamare2112** [comment]
Ah!  I see!  I got confused because the python scripts can use cuda to train but I notice now that OIDN denoise does not :)
