### ISSUE TITLE
Update to OIDN 1.3 (API changes)

### ISSUE THREAD

**Issue by virtualritz** [Twinklebear/oidn-rs#16]
Specifically (from the [changelog](https://github.com/OpenImageDenoise/oidn/releases/tag/v1.3.0))

> * Added `inputScale` filter parameter which generalizes the existing (and thus now deprecated) `hdrScale` parameter for non-HDR images

**Comment by Twinklebear** [comment]
Hey Moritz, thanks for the heads up, I didn't know about this API change. I'm preparing for my phd defense next week so I won't get to this til then but it should be quick to change, but just to note that I'm not ignoring the issue :D

**Comment by virtualritz** [comment]
Best of luck with your defense. I'm not using the API addition/change. I just made the ticket so it doesn't fall through the cracks.

**Comment by Twinklebear** [comment]
This is resolved in e2a6f1c which internally moves to use the `inputScale` parameter and adds `RayTracing::input_scale` to the API. `RayTracing::hdr_scale` is still provided but now has a deprecation warning to avoid making this an API breaking release.
