### ISSUE TITLE
Use 2.0 version instead of 1.4

### ISSUE THREAD

**Issue by nickkuk** [Twinklebear/oidn-rs#18]
In 1.4 there were breaking changes that breaks compilation after `cargo update` due to semver rules. Version 1.4 should be yanked and 2.0 be used instead.

**Comment by Twinklebear** [comment]
Shoot yeah you're right, this is the `FilterError`-> `Error` naming right? I'd prefer to track OIDN version numbers with the crate so it's less confusing, so what I can actually do is push a 1.4.1 that fixes this.

**Comment by Twinklebear** [comment]
Give 1.4.1 a try and let me know how it looks

**Comment by nickkuk** [comment]
Thanks! It helps to my project.

But I've just locally generate documentation for 1.3 and see that there were such top-level reexports:

```
pub use filter::FilterError;
pub use filter::RayTracing;
pub use sys::OIDNAccess as Access;
pub use sys::OIDNDeviceType as DeviceType;
pub use sys::OIDNError as Error;
pub use sys::OIDNFormat as Format;
```

Maybe their absence in 1.4 breaks someone's else code.

**Comment by Twinklebear** [comment]
Great! The raytracing filter is still exported, the ones removed are:

```
pub use sys::OIDNAccess as Access;
pub use sys::OIDNDeviceType as DeviceType;
pub use sys::OIDNError as Error;
pub use sys::OIDNFormat as Format;
```

These weren't actually used in any API methods of the library so I think it should be fine to take them out for now, so I'll close this issue. If it does turn out someone's using these it's easy enough to re-add, though eventually I do want to move `FilterError` -> `Error` and take out exporting that `sys::OIDNError` directly.

**Comment by nickkuk** [comment]
Fair enough. Thanks again!
