### ISSUE TITLE
Error while loading as shared libraries

### ISSUE THREAD

**Issue by lingtorp** [Twinklebear/oidn-rs#2]
I successfully built the bindings and installed OpenImageDenoise using the instructions provided by their Github repo but when starting the my program I get the following error printout: "error while loading shared libraries: libOpenImageDenoise.so.0: cannot open shared object file: No such file or directory".

Symlinked: libOpenImageDenoise.so.0 -> libOpenImageDenoise.so.1.1.0 in /usr/local/lib/ which should be fine given that OIDN_DIR= /usr/local/lib/. Anything that I have missed?

**Comment by Twinklebear** [comment]
Hey @Entalpi , from the error it sounds like `libOpenImageDenoise.so.0` isn't in your `LD_LIBRARY_PATH`? It seems like `/usr/local/lib` should be in the path by default but could you do a quick test of adding it to your `LD_LIBRARY_PATH` (it can vary on some distros)? The dir name stuff is maybe a bit misleading, `OIDN_DIR` is needed at compile time to find the library to link, but at runtime the app uses the regular system library paths.

**Comment by lingtorp** [comment]
Amazingly adding `/usr/local/lib`to `LD_LIBRARY_PATH` worked! For future reference this was done on Ubuntu 18.10. 
Cheers!

**Comment by Twinklebear** [comment]
Good to hear! Yea I forget which distros don't have `/usr/local/lib` in the path by default, but Ubuntu's one of them, it really seems like it should be in there by default.
