### ISSUE TITLE
oidn 2.0 support?

### ISSUE THREAD

**Issue by Elabajaba** [Twinklebear/oidn-rs#22]
Open Image Denoise v2.0.0 was released in May with GPU support for modern AMD, Intel, and Nvidia GPUs on Windows and Linux.

Are there any plans on updating these bindings to support v2.0?

**Comment by Twinklebear** [comment]
It would be great to do, it's just a matter of getting time to do it. If folks are interested in working on it I can also help by reviewing PRs
